name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on:  ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        repository: 'aglowacki/XRF-Maps'
        path: 'XRF-Maps'
    - name: Install Linux Deps
      run: |
        if [ "$RUNNER_OS" != "macOS" ]; then
          sudo apt-get install libdbus-1-dev libxi-dev libxtst-dev bzip2 mingw-w64 libgtk-3-dev libglib2.0-dev libharfbuzz-dev libx11-dev libgles2-mesa-dev linux-libc-dev libxft-dev libxext-dev
        fi
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Install qtbase qtcharts 
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          python -m pip install aqtinstall
          python -m aqt install --outputdir ${{github.workspace}}/Qt 5.15.2 mac desktop clang_64 -m qtcharts --archives qtbase
        else
          python -m pip install aqtinstall
          python -m aqt install --outputdir ${{github.workspace}}/Qt 5.15.2 linux desktop gcc_64 -m qtcharts --archives qtbase
        fi
    - name: Gen vcpkg
      working-directory: ${{github.workspace}}/XRF-Maps/vcpkg
      run: ./bootstrap-vcpkg.sh
    - name: Restore cached vcpkg
      id: cache-vcpkg-restore
      uses: actions/cache/restore@v3
      with:
        path: ${{github.workspace}}/XRF-Maps/vcpkg/installed
        key: ${{ runner.os }}-vcpkg
    - name: Run vcpkg
      if: ${{ steps.cache-vcpkg-restore.outputs.cache-hit != 'true' }}
      working-directory: ${{github.workspace}}/XRF-Maps/vcpkg
      run: ./vcpkg install hdf5 netcdf-c yaml-cpp zeromq jsoncpp opencv tiff
    - name: Save vcpkg cache
      id: cache-vcpkg-save
      uses: actions/cache/save@v3
      with:
        path: ${{github.workspace}}/XRF-Maps/vcpkg/installed
        key: ${{ runner.os }}-vcpkg
    - name: Create XRF Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/XRF-Maps/build
    - name: Configure XRF-Maps CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/XRF-Maps/build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            cmake $GITHUB_WORKSPACE/XRF-Maps -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DQt5_DIR="${{github.workspace}}/Qt/5.15.2/clang_64/lib/cmake/Qt5" -DBUILD_WITH_ZMQ=ON -DBUILD_WITH_QT=ON 
          else
            cmake $GITHUB_WORKSPACE/XRF-Maps -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DQt5_DIR="${{github.workspace}}/Qt/5.15.2/gcc_64/lib/cmake/Qt5" -DBUILD_WITH_ZMQ=ON -DBUILD_WITH_QT=ON -DBUILD_WITH_TIRPC=ON
          fi
    - name: Build XRF-Maps
      working-directory: ${{github.workspace}}/XRF-Maps/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE 
    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/build
    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE=./XRF-Maps/vcpkg/scripts/buildsystems/vcpkg.cmake -DQt5_DIR="${{github.workspace}}/Qt/5.15.2/clang_64/lib/cmake/Qt5" -DXRF_Maps_DIR=${{github.workspace}}/XRF-Maps/build
        else
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE=./XRF-Maps/vcpkg/scripts/buildsystems/vcpkg.cmake -DQt5_DIR="${{github.workspace}}/Qt/5.15.2/gcc_64/lib/cmake/Qt5" -DXRF_Maps_DIR=${{github.workspace}}/XRF-Maps/build
        fi
    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE 
    - name: Cp Ref to Install
      working-directory: ${{github.workspace}}
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        mkdir install
        mkdir install/plugins
        rsync -RavzP reference install
        rsync -RavzP bin install
        if [ "$RUNNER_OS" == "macOS" ]; then
          rsync -RavzP ${{github.workspace}}/Qt/5.15.2/clang_64/plugins/platforms install/plugins
        else
          rsync -RavzP ${{github.workspace}}/Qt/5.15.2/gcc_64/plugins/platforms install/plugins
        fi
        cp ../XRF-Maps/bin install/bin
        cd install
        echo '{"branchName":"${{ github.ref }}","commitHash":"${{ github.sha }}"}' >> version.json
    - uses: actions/upload-artifact@v3
      with:
        name: uProbeX_${{ matrix.os }}_x86_64
        path: ${{github.workspace}}/install/ 
